version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  ton_mongo_data:
  
services:
  app:
    image: ton-transactions-back:0.1.0
    restart: unless-stopped
    build:
      context: .
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - TT_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - TT_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
    labels:
      - traefik.http.routers.app.rule=Host(`api.ton-snow.app`)
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=lets-encrypt
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    volumes:
      - ton_mongo_data:/data/db
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8888:8081"
