version: '3.7'

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  ton_mongo_data:
  
services:
  app:
    image: ton-transactions-back:0.1.2
    restart: unless-stopped
    build:
      context: .
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-debug}
      - TT_MONGODB_AUTH_USERNAME=${TT_MONGODB_AUTH_USERNAME}
      - TT_MONGODB_AUTH_PASSWORD=${TT_MONGODB_AUTH_PASSWORD}
      - TT_MONGODB_DATABASE=${TT_MONGODB_DATABASE}
      - TT_MONGODB_HOST=${TT_MONGODB_HOST}
    labels:
      - traefik.http.routers.app.rule=Host(`api.ton-snow.app`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.tls.certresolver=lets-encrypt
    volumes:
      - ./.env.production:/app/.env.production
    networks:
      - web
      - internal
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TT_MONGODB_AUTH_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${TT_MONGODB_AUTH_PASSWORD}
      - MONGO_INITDB_DATABASE=${TT_MONGODB_DATABASE}
    volumes:
      - ton_mongo_data:/data/db
    networks:
      - internal
    labels:
      - traefik.enable=false
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${TT_MONGODB_AUTH_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${TT_MONGODB_AUTH_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${TT_MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${TT_MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    labels:
      - traefik.enable=false
    networks:
      - internal
      - web
    ports:
      - "8888:8081"
